import { Answer } from './answer';

export const ANSWER: Answer[] = [
  { numero:1,correta: "c",estado: "1",nota:"",respuesta:""},
  { numero:2,correta: "d",estado: "1",nota:"",respuesta:""},
  { numero:3,correta: "c",estado: "1",nota:"",respuesta:""},
  { numero:4,correta: "b",estado: "1",nota:"",respuesta:""},
  { numero:5,correta: "a",estado: "1",nota:"",respuesta:""},
  { numero:6,correta: "b",estado: "1",nota:"",respuesta:""},
  { numero:7,correta: "a",estado: "1",nota:"",respuesta:""},
  { numero:8,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:9,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:10,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:11,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:12,correta: "b",estado: "1",nota:"",respuesta:""},
  { numero:13,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:14,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:15,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:16,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:17,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:18,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:19,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:20,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:21,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:22,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:23,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:24,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:25,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:26,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:27,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:28,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:29,correta: "",estado: "2",nota:"",respuesta:""},
  { numero:30,correta: "",estado: "2",nota:"",respuesta:""},

]
